CREATE TABLE IF NOT EXISTS `feeds` (
  `uuid` UUID NOT NULL DEFAULT uuid (),
  `name` VARCHAR(32) NOT NULL,
  `url` VARCHAR(2048) NOT NULL,
  `modified` TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `disabled` TINYINT (1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`uuid`)
) ENGINE = InnoDB;
